<?php

/**
 * CarriersTableSeeder - Insert info into database.
 *
 * @author   Agustí Dosaiguas
 */
class CarriersTableSeeder extends BaseTableSeeder
{
    protected $table = 'carriers';

    /**
     * Run the database seeds.
     */
    public function run()
    {
        $this->deleteTable();

        $data = [

            [
                'name' => 'verizon',
                'presentation' => 'Verizon',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'verizon',
                'presentation' => 'Verizon1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE1',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'verizon',
                'presentation' => 'Verizon2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE2',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'verizon',
                'presentation' => 'Verizon3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE3',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'verizon',
                'presentation' => 'Verizon4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE4',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'verizon',
                'presentation' => 'Verizon5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'att',
                'presentation' => 'ATT5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bt_mobile',
                'presentation' => 'BT Mobile5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'ipass',
                'presentation' => 'iPass5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],

            [
                'name' => 'rogers',
                'presentation' => 'Rogers5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'sprint',
                'presentation' => 'Sprint5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile',
                'presentation' => 'T-Mobile5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 't_mobile_de',
                'presentation' => 'T-Mobile DE5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
            [
                'name' => 'us_cellular',
                'presentation' => 'US Cellular5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'system',
                'presentation' => 'System5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 236,
            ],
            [
                'name' => 'bell_canada',
                'presentataion' => 'BellCanada5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 40,
            ],
            [
                'name' => 'vodafone_uk',
                'presentation' => 'VodafoneUK5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 235,
            ],
            [
                'name' => 'vodafone_de',
                'presentation' => 'VodafoneDE5',
                'active' => 1,
                'shortName' => 'shortname',
                'locationId' => 83,
            ],
        ];

        $this->loadTable($data);
    }
}
