version: 2.1
executors:
  clean:
    working_directory: ~/WirelessAnalytics/clean-api
    docker:
        - image: circleci/php:7.1-node-browsers
jobs:
  build:
    executor: clean
    steps:
    - checkout
    - run: sudo apt install -y libsqlite3-dev zlib1g-dev libmcrypt-dev ruby
    - run: sudo docker-php-ext-install zip
    - run: sudo docker-php-ext-install mcrypt
    - run: sudo composer self-update
    - run: sudo gem install bundler
    - run: mkdir -p build/logs/coverage_html
    - run: composer install --prefer-source --no-interaction
    - run: bundle install
    - run: chmod 600 ~/WirelessAnalytics/clean-api/storage/oauth-private.key
    - run: cp .env.test .env
    - persist_to_workspace:
        root: build
        paths:
            - logs
  test_integration_admin:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=1 php vendor/bin/phpunit -c phpunit.xml --testsuite "Integration Tests" --exclude-group need-review --coverage-clover build/logs/clover-integration-admin.xml -d memory_limit=2048M
  test_integration_wta:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=2 php vendor/bin/phpunit -c phpunit.xml --testsuite "Integration Tests" --exclude-group need-review --coverage-clover build/logs/clover-integration-wta.xml -d memory_limit=2048M
  test_integration_user:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=3 php vendor/bin/phpunit -c phpunit.xml --testsuite "Integration Tests" --exclude-group need-review --coverage-clover build/logs/clover-integration-user.xml -d memory_limit=2048M
  test_unit_admin:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=1 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-unit-admin.xml -d memory_limit=2048M
  test_unit_wta:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=2 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-unit-wta.xml -d memory_limit=2048M
  test_unit_user:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=3 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-unit-user.xml -d memory_limit=2048M
  test_other_admin:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=1 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-other-admin.xml -d memory_limit=2048M
  test_other_wta:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=2 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-other-wta.xml -d memory_limit=2048M
  test_other_user:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: CLEAN_TEST_USER=3 php vendor/bin/phpunit -c phpunit.xml --testsuite "Unit Tests" --exclude-group need-review --coverage-clover build/logs/clover-other-user.xml -d memory_limit=2048M
  coveralls:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: php vendor/bin/php-coveralls -v
  deployment:
    executor: clean
    steps:
    - attach_workspace:
        at: build
    - run: bundle exec cap develop deploy
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test_integration_admin:
          requires:
            - build
      - test_integration_wta:
          requires:
            - build
      - test_integration_user:
          requires:
            - build
      - test_unit_admin:
          requires:
            - build
      - test_unit_wta:
          requires:
            - build
      - test_unit_user:
          requires:
            - build
      - test_other_admin:
          requires:
            - build
      - test_other_wta:
          requires:
            - build
      - test_other_user:
          requires:
            - build
      - coveralls:
          requires:
            - test_integration_admin
            - test_integration_wta
            - test_integration_user
            - test_unit_admin
            - test_unit_wta
            - test_unit_user
            - test_other_admin
            - test_other_wta
            - test_other_user
      - deployment:
          requires:
            - coveralls
          filters:
            branches:
              only: master